### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by michiexile** [appliedtopology/circular-coordinates#10]
https://github.com/appliedtopology/circular-coordinates/blob/7e8f7961903686fb30e53b9a57d141e67153a4c2/circularcoordinates/circular_coordinates.py#L238

It's not clear from the docstring what the `Max` choice does, and what this `intr` parameter really controls.

**Comment by bilalze** [comment]
Max bins for epsilons over the longest barcode. intr specifies the number of samples (default is 10)

**Comment by bilalze** [comment]
I have changed the structure for the scikit branch it does not do this now.
