### ISSUE TITLE
Recursive call without `arg_eps`?

### ISSUE THREAD

**Issue by michiexile** [appliedtopology/circular-coordinates#11]
https://github.com/appliedtopology/circular-coordinates/blob/7e8f7961903686fb30e53b9a57d141e67153a4c2/circularcoordinates/circular_coordinates.py#L250

This recursive call seems to drop `arg_eps` (as well as all other parameters). Is this supposed to be that way?

**Comment by bilalze** [comment]
yes, it is done to find the circular coordinates for epsilon(or longest barcode). This is used for comparison with binned max and all circular coordinates

**Comment by bilalze** [comment]
I have changed the structure for the scikit branch it does not do this now.
